version: '2'

services:
  capi:
    image: rbkmoney/build:latest
    volumes:
      - .:/code
    working_dir: /code
    command: /sbin/init

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
